import React from 'react'
import { useStudy } from '../../context/StudyContext'
import {
  BookOpen,
  CheckCircle2,
  Lightbulb,
  Download,
  Share2,
  Layers,
  HelpCircle,
  FileSpreadsheet,
  GraduationCap
} from 'lucide-react'

export default function StudySummaryView() {
  const { activeSet, setCurrentView } = useStudy()

  if (!activeSet || !activeSet.summary) {
    return (
      <div className="text-center py-20">
        <p className="text-slate-400 mb-4">No summary generated for this deck.</p>
        <button
          onClick={() => setCurrentView('create')}
          className="px-6 py-2.5 rounded-xl bg-brand-600 text-white font-semibold text-xs"
        >
          Create New Study Pack
        </button>
      </div>
    )
  }

  const { overview, keyPoints = [], examTips = [], cheatSheet = [] } = activeSet.summary

  // Export to markdown download
  const handleExportMarkdown = () => {
    let md = `# ${activeSet.title}\n`
    md += `*Generated by Draft AI*\n\n`
    md += `## Executive Overview\n${overview}\n\n`
    md += `## High-Yield Key Points\n`
    keyPoints.forEach((kp) => (md += `- ${kp}\n`))
    md += `\n## Exam Tips\n`
    examTips.forEach((tip) => (md += `- ${tip}\n`))

    if (cheatSheet.length > 0) {
      md += `\n## Quick Revision Cheat Sheet\n`
      cheatSheet.forEach((item) => {
        md += `- **${item.concept}**: ${item.formula} *(${item.note})*\n`
      })
    }

    if (activeSet.flashcards) {
      md += `\n## Flashcards (${activeSet.flashcards.length})\n`
      activeSet.flashcards.forEach((fc) => {
        md += `### ${fc.term}\n${fc.definition}\n\n`
      })
    }

    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${activeSet.title.replace(/[^a-zA-Z0-9]/g, '_')}_study_pack.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-4xl mx-auto py-6 space-y-8 animate-fadein">
      
      {/* Set Header Card */}
      <div className="p-8 rounded-3xl bg-gradient-to-r from-dark-900 via-dark-850 to-dark-900 border border-white/[0.08] shadow-card flex flex-col sm:flex-row sm:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 text-xs text-brand-400 font-semibold mb-2">
            <GraduationCap className="w-4 h-4" />
            <span>{activeSet.subject || 'Academic Revision'}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            {activeSet.title}
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            {activeSet.cardCount || activeSet.flashcards?.length || 0} Flashcards • {activeSet.quizCount || activeSet.quiz?.length || 0} MCQs
          </p>
        </div>

        {/* Quick Launch & Export Actions */}
        <div className="flex items-center gap-2.5 shrink-0">
          <button
            onClick={handleExportMarkdown}
            className="p-3 rounded-2xl bg-white/[0.04] hover:bg-white/[0.08] text-slate-300 hover:text-white border border-white/10 flex items-center gap-2 text-xs font-semibold transition-colors"
            title="Download as Markdown"
          >
            <Download className="w-4 h-4" />
            <span>Export Notes</span>
          </button>

          <button
            onClick={() => setCurrentView('flashcards')}
            className="px-4 py-3 rounded-2xl bg-brand-600 hover:bg-brand-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-glow-brand transition-all"
          >
            <Layers className="w-4 h-4" />
            <span>Practice Cards</span>
          </button>
        </div>
      </div>

      {/* Executive Overview */}
      <div className="p-7 rounded-3xl bg-dark-900 border border-white/[0.08] shadow-card">
        <div className="flex items-center gap-2 mb-3 text-sm font-bold text-white">
          <BookOpen className="w-5 h-5 text-brand-400" />
          <span>Executive Overview</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          {overview}
        </p>
      </div>

      {/* Key Points Grid */}
      <div className="p-7 rounded-3xl bg-dark-900 border border-white/[0.08] shadow-card">
        <div className="flex items-center gap-2 mb-4 text-sm font-bold text-white">
          <CheckCircle2 className="w-5 h-5 text-emerald-400" />
          <span>Core Concepts & Principles</span>
        </div>
        <div className="space-y-3">
          {keyPoints.map((pt, idx) => (
            <div key={idx} className="flex items-start gap-3 p-3 rounded-2xl bg-dark-950/60 border border-white/[0.04]">
              <span className="w-5 h-5 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center font-mono text-[11px] font-bold shrink-0 mt-0.5">
                {idx + 1}
              </span>
              <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">{pt}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Exam Tips Box */}
      <div className="p-7 rounded-3xl bg-dark-900 border border-gold-500/25 shadow-glow-gold/10">
        <div className="flex items-center gap-2 mb-4 text-sm font-bold text-gold-400">
          <Lightbulb className="w-5 h-5" />
          <span>High-Yield Exam Tips</span>
        </div>
        <div className="space-y-2.5">
          {examTips.map((tip, idx) => (
            <div key={idx} className="p-3.5 rounded-2xl bg-gold-500/[0.04] border border-gold-500/15 text-xs sm:text-sm text-slate-200 leading-relaxed">
              ⭐ {tip}
            </div>
          ))}
        </div>
      </div>

      {/* Formula / Concept Cheat Sheet */}
      {cheatSheet.length > 0 && (
        <div className="p-7 rounded-3xl bg-dark-900 border border-white/[0.08] shadow-card">
          <div className="flex items-center gap-2 mb-4 text-sm font-bold text-white">
            <FileSpreadsheet className="w-5 h-5 text-indigo-400" />
            <span>Quick Revision Cheat Sheet</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-white/[0.08] text-slate-400">
                  <th className="pb-3 font-semibold">Concept</th>
                  <th className="pb-3 font-semibold">Formula / Key Rule</th>
                  <th className="pb-3 font-semibold">Exam Note</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.04]">
                {cheatSheet.map((item, idx) => (
                  <tr key={idx} className="hover:bg-white/[0.02]">
                    <td className="py-3 font-bold text-white pr-4">{item.concept}</td>
                    <td className="py-3 font-mono text-brand-300 pr-4">{item.formula}</td>
                    <td className="py-3 text-slate-400">{item.note}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Bottom Launch Callouts */}
      <div className="p-8 rounded-3xl bg-gradient-to-br from-dark-850 to-dark-900 border border-white/10 text-center space-y-4">
        <h3 className="text-lg font-bold text-white">Ready to cement your memory?</h3>
        <p className="text-xs text-slate-400 max-w-md mx-auto">
          Reading is only the first step. Switch to active recall or test yourself against timed questions.
        </p>
        <div className="flex justify-center gap-3 pt-2">
          <button
            onClick={() => setCurrentView('flashcards')}
            className="px-6 py-3 rounded-2xl bg-brand-600 hover:bg-brand-500 text-white font-bold text-xs flex items-center gap-2 shadow-glow-brand"
          >
            <Layers className="w-4 h-4" />
            <span>Study Flashcards</span>
          </button>
          <button
            onClick={() => setCurrentView('quiz')}
            className="px-6 py-3 rounded-2xl bg-gold-500 hover:bg-gold-400 text-dark-950 font-bold text-xs flex items-center gap-2 shadow-glow-gold"
          >
            <HelpCircle className="w-4 h-4" />
            <span>Take Practice Quiz</span>
          </button>
        </div>
      </div>

    </div>
  )
}

